name: NoxetServer
version: '${project.version}'
main: org.noxet.noxetserver.NoxetServer
api-version: '1.20'
author: dumburk
commands:
  hub:
    description: Go to the hub
    usage: /hub
    aliases:
      - leave
      - lobby
      - l
  spawn:
    description: Go to spawn
    usage: /spawn
  smp:
    description: Join the SMP server
    usage: /smp
    aliases:
      - survival
  anarchy:
    description: Join the Anarchy server
    usage: /anarchy
  wild:
    description: Enter the wilderness...
    usage: /wild
    aliases:
      - wilderness
      - rtp
      - touch-grass
  tpa:
    description: Send/accept/deny/cancel a teleportation request to/from a player
    usage: /tpa <player|cancel|accept|deny|toggle-allow-incoming> [player|*]
  whereami:
    description: Check what world and realm you are in
    usage: /whereami
  games:
    description: Choose from games to play
    usage: /games
    aliases:
      - play
      - lets-go
  home:
    description: Teleport to/manage homes
    usage: /home <tp|set|remove|list|rename|friend-tp> [home name|friend's home] [(for rename) new home name]
    aliases:
      - h
  chickenleg:
    description: chicken leg.
    usage: /chickenleg
  doas:
    description: Command impersonation command
    usage: /doas <player> <command> [args...]
  mute:
    description: Mute a player
    usage: /mute <player>
  unmute:
    description: Unmute a player
    usage: /unmute <player>
  msg:
    description: Talk privately to a player
    usage: /msg <player|toggle> [message]
    aliases:
      - message
      - talk
      - tell
      - whisper
      - dm
  toggle-preserve:
    description: Toggles a preserved world
    usage: /toggle-preserve
  canvas-world:
    description: Go to creative world
    usage: /creative-world
  loop:
    description: Repeat a command an amount of times
    usage: /loop <amount> <command> [args...]
  set-realm-spawn:
    description: Set the realm spawn to your location
    usage: /set-realm-spawn
  reset-realm-spawn:
    description: Reset the realm's spawn location
    usage: /reset-realm-spawn
  friend:
    description: Manage relationships
    usage: /friend <add|remove|deny|cancel|list|incoming|outgoing|toggle-allow-incoming|toggle-friend-tp> [player]
    aliases:
      - f
  block:
    description: Block a player
    usage: /block <player>
  unblock:
    description: Unblock a player
    usage: /unblock <player>
  block-list:
    description: Lists players you have blocked
    usage: /block-list
  clear-player-data-cache:
    description: Clear all player's cached data
    usage: /clear-player-data-cache
  fake-combat-log:
    description: Simulate a combat log (when you hit or get hit by a player)
    usage: /fake-combat-log
  creeper-sweeper:
    description: Play a game of Creeper Sweeper
    usage: /creeper-sweeper
    aliases:
      - crsw
  clear-creeper-sweeper-stats:
    description: Clear your Creeper Sweeper statistics (wins/losses/average)
    usage: /clear-creeper-sweeper-stats
  enderchest:
    description: Access your inventory while mobile!
    usage: /enderchest [player]
    aliases:
      - ec
      - echest
  game:
    description: Manage mini-games
    usage: /game <play|join|leave|spectate|info|list|stop|debug-create> [mini-game|ID|soft|hard]
  party:
    description: Manage a party of players
    usage: /party <create|invite|chat|accept|deny|kick|transfer|leave|list|disband|kick-busy|toggle-invites> [player|message]
    aliases:
      - p